---
title: "Demonstrate performance of [GenomicDataStream](https://gabrielhoffman.github.io/GenomicDataStream/)"
subtitle: 'DelayedMatrix'
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r Sys.time()`"
output: 
  html_document:
    toc: true
    smart: true
    self_contained: true
---

<!---


# rm -rf demo_matrix_cache/

rmarkdown::render("demo_matrix.Rmd");

# Memory profiling
/usr/bin/time -l /Users/gabrielhoffman/prog/R-4.4.2/bin/R

# Max mem usage reported in bytes, so divide by 1e-9
#  maximum resident set size

# peakRAM doesn't give correct value

--->


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  dev = c("png", "pdf"),
  package.startup.message = FALSE,
  cache = TRUE,
  cache.lazy = FALSE)
```


```{r load, cache=FALSE}
suppressPackageStartupMessages({
library(DelayedArray)
library(zellkonverter)
library(SingleCellExperiment)
library(RUnit)
library(DelayedMatrixStats)
library(BiocSingular)
library(ggplot2)
library(GenomicDataStream)
library(tidyverse)
})

file = "~/Downloads/4e6932db-5a78-40e4-b961-f87f66ba139a.h5ad"
# file = "~/4e6932db-5a78-40e4-b961-f87f66ba139a.h5ad"
sce_in = readH5AD(file, use_hdf5=TRUE, raw=TRUE, verbose=TRUE, uns=FALSE, obsp=FALSE, obsm=FALSE)
sce <- swapAltExp(sce_in, "raw") 
counts(sce) <- assay(sce, "X") 
sce$total_counts = colSums2(counts(sce))

lib.size = sce$total_counts
prior.count = 1
logcounts(sce) <- t(log2(t(counts(sce) + prior.count)) - log2(lib.size) + log2(1e6))
```

# Accuracy
```{r accuracy}
k = 50
sceSub = sce[seq(1000),]

X = t(logcounts(sceSub))
X_scale = scale(X) / sqrt(nrow(X) -1)
dcmp <- svd( X_scale, k)

res <- PCAstream(sceSub, k)
```

```{r accuracyPlot, cache=FALSE, fig.height=8, fig.width=8}
stat = sapply(seq(k), function(i){
  perfMetric(dcmp$u[,seq(i),drop=FALSE], res$u[,seq(i),drop=FALSE], metric = "MEV")
})
par(pty="s", mfrow=c(2,2))
plot(seq(k), stat, ylim=c(0,1), xlab="Principal component index", ylab="Mean explained variance")

plot(dcmp$d[seq(k)], res$d, log="xy", xlab="True singular values (log)", ylab="Estimated singular values (log)")
abline(0, 1, col="red")

stat = sapply(seq(k), function(i){
  perfMetric(dcmp$u[,seq(i),drop=FALSE], res$u[,seq(i),drop=FALSE], metric = "minSSE")
})
plot(seq(k), stat, xlab="Principal component index", ylab="Minimum of sum of squared errors")

fracExpl = dcmp$d[seq(k)]^2 / sum(dcmp$d^2)
plot( fracExpl , stat, xlab="Fraction of variance explained by PC (log scale)", ylab="Minimum of sum of squared errors", log="x")
```




# Time vs number of genes
```{r numGenes}
k = 20

n_features = c(1000, 2000, 5000, 10000, nrow(sce))

res = lapply(n_features, function(p){

  res_time = system.time({
    res <- PCAstream(sce[seq(p),], k, threads=4)
  })

  data.frame(n_features = p, t(data.frame(res_time)))
})
res = do.call(rbind, res)
```

```{r numGenesPlot, cache=FALSE}
ggplot(res, aes(n_features, elapsed)) +
  geom_point() +
  theme_classic() +
  theme(aspect.ratio=1) +
  ylab("Time (seconds)")

```



# Time vs number of cells
```{r numCells}
k = 20

n_cells = c(1000, 5000, 20000, ncol(sce))

res = lapply(n_cells, function(nc){

  res_time = system.time({
    res <- PCAstream(sce[,seq(nc)], k, threads=4)
  })

  data.frame(nc = nc, t(data.frame(res_time)))
})
res = do.call(rbind, res)
```

```{r numCellsPlot, cache=FALSE}
ggplot(res, aes(nc, elapsed)) +
  geom_point() +
  theme_classic() +
  theme(aspect.ratio=1) +
  ylab("Time (seconds)")

```



# Time vs number of threads
```{r nThreads}
k = 20
res = lapply(c(1,2,4,6), function(threads){

  res_time = system.time({
    res <- PCAstream(sce, k, threads=threads)
  })

  data.frame(threads=threads, t(data.frame(res_time)))
})
res = do.call(rbind, res)
```


```{r nThreadsPlot, cache=FALSE}
ggplot(res, aes(threads, elapsed )) +
  geom_point() +
  theme_classic() +
  theme(aspect.ratio=1, legend.position="none") +
  ylab("Time (seconds)")
```



# Time vs number of PCs

```{r nPCs, message=FALSE}
k_array = c(2, 5, seq(10, 110, by=20), 
        seq(125, 200, by=25))

res = lapply(k_array, function(k){

  res_time = system.time({
    res <- PCAstream(sce, k, threads=4)
  })

  data.frame(k=k, t(data.frame(res_time)), Method="PCAstream")
})
res = do.call(rbind, res)
```



```{r nPcsPlot, cache=FALSE}
res %>%
  ggplot(aes(k, elapsed, color=Method )) +
    geom_point() +
    theme_classic() +
    theme(aspect.ratio=1, legend.position="right") +
    ylab("Time (seconds)")
```



# Compare Methods
```{r compareMethods, message=FALSE}
ngenes = 10000
ncells = c(1000, 2000, 5000, seq(10000, 60000, by=10000))
k = 50

res = lapply(ncells, function(nc){

  sceSub = sce[seq(ngenes),seq(nc)]

  res_time = system.time({
    res <- PCAstream(sceSub, k, threads=4)
  })

  data.frame(ncells = nc, t(data.frame(res_time)), Method="PCAstream")
})
res = do.call(rbind, res)

# runSVD
res2 = lapply(ncells, function(nc){

  sceSub = sce[seq(ngenes),seq(nc)]

  res_time_0 = NULL
  res_time_1 = NULL
  res_time_2 = NULL

  # if( k < 100 ){
  #   res_time_0 = system.time({
  #     out <- runSVD( t(logcounts(sce)), k=k, center=TRUE, scale=TRUE, BSPARAM=ExactParam())
  #   })
  #   res_time_0 = t(data.frame(res_time_0)) %>%
  #               data.frame(Method = "Exact SVD")
  # }

  if( nc <= 5000 ){
    res_time_1 = system.time({
      out <- runSVD( t(logcounts(sceSub)), k=k, center=TRUE, scale=TRUE, BSPARAM=IrlbaParam())
    })
    res_time_1 = t(data.frame(res_time_1)) %>%
                data.frame(Method = "IRLBA")
  }

  res_time_2 = system.time({
    out <- runSVD( t(logcounts(sceSub)), k=k, center=TRUE, scale=TRUE, BSPARAM=RandomParam())
  })
  res_time_2 = t(data.frame(res_time_2)) %>%
              data.frame(Method = "Randomized SVD")

  rbind(res_time_0, res_time_1, res_time_2) %>%
  data.frame(ncells = nc, .)
})
res2 = do.call(rbind, res2)
```



```{r compareMethodsPlot, cache=FALSE}
rbind(res, res2) %>%
  mutate(Method = factor(Method, c("IRLBA", "Randomized SVD", "PCAstream"))) %>%
  ggplot(aes(ncells, elapsed, color=Method )) +
    geom_smooth(method="lm", se=FALSE) +
    geom_point(size=4) +
    theme_bw() +
    theme(aspect.ratio=1, legend.position="right") +
    ylab("Time (seconds)") +
    xlab("Number of cells") + 
    scale_x_log10()+ 
    scale_y_log10()
```








