# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_center_and_scale <- function(mat, nthreads) {
    .Call('_GenomicDataStream_compute_center_and_scale', PACKAGE = 'GenomicDataStream', mat, nthreads)
}

create_xptr <- function(file, field = "", region = "", samples = "-", MAF = 0, minVariance = 0, chunkSize = 10000L, missingToMean = TRUE) {
    .Call('_GenomicDataStream_create_xptr', PACKAGE = 'GenomicDataStream', file, field, region, samples, MAF, minVariance, chunkSize, missingToMean)
}

getInfo <- function(x) {
    .Call('_GenomicDataStream_getInfo', PACKAGE = 'GenomicDataStream', x)
}

setRegions_rcpp <- function(x, regionString) {
    .Call('_GenomicDataStream_setRegions_rcpp', PACKAGE = 'GenomicDataStream', x, regionString)
}

setChunkSize_rcpp <- function(x, chunkSize) {
    .Call('_GenomicDataStream_setChunkSize_rcpp', PACKAGE = 'GenomicDataStream', x, chunkSize)
}

getSampleNames_rcpp <- function(x) {
    .Call('_GenomicDataStream_getSampleNames_rcpp', PACKAGE = 'GenomicDataStream', x)
}

atEndOfStream_rcpp <- function(x) {
    .Call('_GenomicDataStream_atEndOfStream_rcpp', PACKAGE = 'GenomicDataStream', x)
}

featuresRead_rcpp <- function(x) {
    .Call('_GenomicDataStream_featuresRead_rcpp', PACKAGE = 'GenomicDataStream', x)
}

getNextChunk_rcpp <- function(x) {
    .Call('_GenomicDataStream_getNextChunk_rcpp', PACKAGE = 'GenomicDataStream', x)
}

summarizeChunks_rcpp <- function(x) {
    .Call('_GenomicDataStream_summarizeChunks_rcpp', PACKAGE = 'GenomicDataStream', x)
}

colSums_test <- function(X) {
    .Call('_GenomicDataStream_colSums_test', PACKAGE = 'GenomicDataStream', X)
}

.standardize_in_place <- function(X, center = TRUE, scale = TRUE) {
    invisible(.Call('_GenomicDataStream_standardize_in_place', PACKAGE = 'GenomicDataStream', X, center, scale))
}

test_DataTable <- function(file, headerKey, delim = "\t ") {
    invisible(.Call('_GenomicDataStream_test_DataTable', PACKAGE = 'GenomicDataStream', file, headerKey, delim))
}

stream_pcaone <- function(x, region, m, k, nchunks, s = 20L, p = 7L, B = 64L, threads = 4L, threads_eigen = 4L, verbose = TRUE, scaleAndCenter = TRUE) {
    .Call('_GenomicDataStream_stream_pcaone', PACKAGE = 'GenomicDataStream', x, region, m, k, nchunks, s, p, B, threads, threads_eigen, verbose, scaleAndCenter)
}

stream_pcaone_robj <- function(x, ids, n, chunkSize, nchunks, m, k, s = 20L, p = 7L, B = 64L, threads = 4L, threads_eigen = 1L, verbose = TRUE, scaleAndCenter = TRUE) {
    .Call('_GenomicDataStream_stream_pcaone_robj', PACKAGE = 'GenomicDataStream', x, ids, n, chunkSize, nchunks, m, k, s, p, B, threads, threads_eigen, verbose, scaleAndCenter)
}

