# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

extractVcf <- function(file, field, region = "", samples = "-", missingToMean = FALSE) {
    .Call('_GenomicDataStream_extractVcf', PACKAGE = 'GenomicDataStream', file, field, region, samples, missingToMean)
}

extractVcf_eigen <- function(file, field, region = "", samples = "-", missingToMean = FALSE) {
    .Call('_GenomicDataStream_extractVcf_eigen', PACKAGE = 'GenomicDataStream', file, field, region, samples, missingToMean)
}

extractVcf_NM <- function(file, field, region = "", samples = "-", missingToMean = FALSE) {
    .Call('_GenomicDataStream_extractVcf_NM', PACKAGE = 'GenomicDataStream', file, field, region, samples, missingToMean)
}

extractVcf_vector <- function(file, field, region = "", samples = "-", missingToMean = FALSE) {
    .Call('_GenomicDataStream_extractVcf_vector', PACKAGE = 'GenomicDataStream', file, field, region, samples, missingToMean)
}

extractVcf_chunks <- function(file, field, region = "", samples = "-", missingToMean = FALSE) {
    .Call('_GenomicDataStream_extractVcf_chunks', PACKAGE = 'GenomicDataStream', file, field, region, samples, missingToMean)
}

getDosage <- function(file, field, region = "", samples = "-", chunkSize, missingToMean = FALSE) {
    .Call('_GenomicDataStream_getDosage', PACKAGE = 'GenomicDataStream', file, field, region, samples, chunkSize, missingToMean)
}

colSums_test <- function(X) {
    .Call('_GenomicDataStream_colSums_test', PACKAGE = 'GenomicDataStream', X)
}

standardize_test <- function(X, center = TRUE, scale = TRUE) {
    invisible(.Call('_GenomicDataStream_standardize_test', PACKAGE = 'GenomicDataStream', X, center, scale))
}

fastLM_eigen <- function(y, file, field, region = "", samples = "-", chunkSize = 4L, missingToMean = FALSE) {
    .Call('_GenomicDataStream_fastLM_eigen', PACKAGE = 'GenomicDataStream', y, file, field, region, samples, chunkSize, missingToMean)
}

fastLM <- function(y, file, field, region = "", samples = "-", chunkSize = 4L, missingToMean = FALSE) {
    .Call('_GenomicDataStream_fastLM', PACKAGE = 'GenomicDataStream', y, file, field, region, samples, chunkSize, missingToMean)
}

